services:
  db:
    image: postgres:16
    container_name: emotionsai_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  web:
    build: .
    container_name: emotionsai_backend
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - media_files:/app/server/media
    depends_on:
      - db
    networks:
      - backend_network
      - emotion_shared
    command: python server/manage.py runserver 0.0.0.0:8001

  nginx:
    image: nginx:alpine
    container_name: emotionsai_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - media_files:/app/server/media:ro
    depends_on:
      - web
    networks:
      - backend_network

volumes:
  postgres_data:
  media_files:

networks:
  backend_network:
    driver: bridge
  emotion_shared:
    external: true
